# Generated by Django 3.1.14 on 2022-07-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20220701_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evoluted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
