# Generated by Django 3.1.14 on 2022-07-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20220701_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evoluted_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolved_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolved_to', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
